"""added connection recoreds

Revision ID: f04f4a75234
Revises: 594dc921b04e
Create Date: 2015-01-30 15:09:13.974233

"""

# revision identifiers, used by Alembic.
revision = 'f04f4a75234'
down_revision = '594dc921b04e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_records',
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_records')
    ### end Alembic commands ###
